version: "3.7"
services:
  smarthub:
    build:
      dockerfile: ./Dockerfile
      context: "."
    restart: always
    ports:
      - "7100:7100"
    depends_on:
      - db
    volumes:
      - .:/usr/src/app

  db:
    image: postgres:9.6.19-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=smarthub
    ports:
      - 5432:5432
    volumes:
      - .:/usr/src/pgdata/data

  redis-service:
    image: redis:alpine3.12
    ports:
      - 6379:6379
    volumes:
      - .:/usr/src/redis/redisdata
